name: Python Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.8"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip xvfb

      - name: Setup Chrome and ChromeDriver
        run: |
          # Chrome o'rnatish
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Chrome versiyasini olish
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Installed Chrome version: $CHROME_VERSION"
          
          # ChromeDriver uchun major versiyani ajratib olish
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
          echo "Chrome major version: $CHROME_MAJOR_VERSION"
          
          # ChromeDriver versiyasini aniqlash
          if [ "$CHROME_MAJOR_VERSION" -ge "115" ]; then
            # Chrome 115+ uchun yangi API
            CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
            DOWNLOAD_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
            echo "Using new API. ChromeDriver version: $CHROMEDRIVER_VERSION"
          else
            # Eski Chrome versiyalari uchun
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
            DOWNLOAD_URL="https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
            echo "Using legacy API. ChromeDriver version: $CHROMEDRIVER_VERSION"
          fi
          
          # ChromeDriver yuklab olish va o'rnatish
          echo "Downloading ChromeDriver from: $DOWNLOAD_URL"
          wget -O chromedriver.zip "$DOWNLOAD_URL"
          
          unzip chromedriver.zip
          
          # Fayl nomini tekshirish va to'g'ri joylash
          if [ -f "chromedriver-linux64/chromedriver" ]; then
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          elif [ -f "chromedriver" ]; then
            sudo mv chromedriver /usr/local/bin/
          else
            echo "ChromeDriver fayl topilmadi!"
            ls -la
            exit 1
          fi
          
          sudo chmod +x /usr/local/bin/chromedriver
          
          # O'rnatishni tekshirish
          echo "Verifying installation..."
          google-chrome --version
          chromedriver --version
          
          # Tozalash
          rm -f chromedriver.zip
          rm -rf chromedriver-linux64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests (headless on CI)
        env:
          HEADLESS: "1"
          DISPLAY: ":99"
        run: |
          # Virtual display ishga tushirish
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3
          
          # Testlarni ishga tushirish
          pytest -v -s --maxfail=1 --tb=short --html=reports/report.html --self-contained-html

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/